### ISSUE TITLE
pub finished with exit code 65

### ISSUE THREAD

**Issue by BirdyF** [dart-lang/pub#2092]
I am trying to publish my first package (https://github.com/BirdyF/strava_flutter)  and have the following error:
pub finished with exit code 65

When running flutter packages pub publish --dry-run --verbose the detailed error is:
  | Nothing output on stderr.
IO  : Reading binary file ./README.md.
IO  : Read 1537 bytes from ./README.md.
IO  : Spawning "tar --format=ustar --create --gzip --directory /Users/user/Documents/Flutter/packages/strava_flutter/. @/dev/stdin" in /Users/user/Documents/Flutter/packages/strava_flutter/.
WARN: Suggestions:
WARN: * The name of "lib/API/Oauth.dart", "Oauth", should be lower-case. Maybe use "oauth"?
WARN: * The name of "lib/Models/detailedActivity.dart", "detailedActivity", should be lower-case. Maybe use "detailed_activity"?
WARN: * The name of "lib/Models/detailedAthlete.dart", "detailedAthlete", should be lower-case. Maybe use "detailed_athlete"?
WARN: * The name of "lib/Models/runningRace.dart", "runningRace", should be lower-case. Maybe use "running_race"?
WARN: * The name of "lib/Models/startSegment.dart", "startSegment", should be lower-case. Maybe use "start_segment"?
WARN: * The name of "lib/Models/summaryActivity.dart", "summaryActivity", should be lower-case. Maybe use "summary_activity"?
WARN: * The name of "lib/Models/summaryAthlete.dart", "summaryAthlete", should be lower-case. Maybe use "summary_athlete"?
WARN: * The name of "lib/Models/uploadActivity.dart", "uploadActivity", should be lower-case. Maybe use "upload_activity"?
WARN:
    | Package has 8 warnings.
pub finished with exit code 65

 
#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      pubInteractively (package:flutter_tools/src/dart/pub.dart:186:5)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:148:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#10     Future._complete (dart:async/future_impl.dart:473:7)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#12     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

Here is below flutter doctor 
[✓] Flutter (Channel stable, v1.0.1-pre.2, on Mac OS X 10.13.6 17G3025, locale en-BE)
    • Flutter version 1.0.1-pre.2 at /Users/user/Documents/Flutter/flutter
    • Framework revision 27cb0aca17 (32 minutes ago), 2019-03-05 09:47:35 +0100
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • ANE LX1 • 89UDU18531001686 • android-arm64 • Android 8.0.0 (API 26)

Not sure what I have done incorrectly

**Comment by jonasfj** [comment]
@BirdyF, could you do the following in your terminal:
 * `which tar`
 * `which gzip`

Based on a  previous issue I'm wondering if maybe we have a dependency on the system having gzip installed... If so, it might be something you can fix with `brew install gzip`. But please check if you have `tar` and `gzip` on the system first, and if this is indeed the bug... then we should fix it in `pub` by using the gzip implementation we have in Dart :)

(this was just a guess, based on another issue I've seen)

**Comment by BirdyF** [comment]
Please find below:

27-iMac:~ user$ which tar
/usr/bin/tar
27-iMac:~ user$ which gzip
/usr/bin/gzip
27-iMac:~ user$ 

gzip version is Apple gzip 272
tar version is bsdtar 2.8.3 - libarchive 2.8.3

Let me know if I can do anything else.

**Comment by BirdyF** [comment]
I still have this problem exit code 65 when running in dry run BUT when running for real:
 flutter packages pub publish
I dont have this issue and I have been able to successfully publish my package.

**Comment by jonasfj** [comment]
@BirdyF, is dry-run broken for your package specifically, or what happens if you try dry-run for another package? We would be curious to fix this if dry-run publishing is broken...

**Comment by BirdyF** [comment]
@jonasfj Can I clone an existing package and do a dry-run for this package or do I have to create another package?

**Comment by jonasfj** [comment]
@BirdyF, you can try to clone `https://github.com/dart-lang/convert`

You should be able to run `pub publish --dry-run` and get:
```
[convert]$pub publish --dry-run
Publishing convert 2.1.1 to https://pub.dartlang.org:
|-- .gitignore
|-- .test_config
|-- .travis.yml
|-- AUTHORS
|-- CHANGELOG.md
|-- CONTRIBUTING.md
|-- LICENSE
|-- README.md
|-- codereview.settings
|-- lib
|   |-- convert.dart
|   '-- src
|       |-- accumulator_sink.dart
|       |-- byte_accumulator_sink.dart
|       |-- hex
|       |   |-- decoder.dart
|       |   '-- encoder.dart
|       |-- hex.dart
|       |-- identity_codec.dart
|       |-- percent
|       |   |-- decoder.dart
|       |   '-- encoder.dart
|       |-- percent.dart
|       |-- string_accumulator_sink.dart
|       '-- utils.dart
|-- pubspec.yaml
'-- test
    |-- accumulator_sink_test.dart
    |-- byte_accumulator_sink_test.dart
    |-- hex_test.dart
    |-- identity_codec_test.dart
    |-- percent_test.dart
    '-- string_accumulator_sink_test.dart

Package has 0 warnings.
```

Hopefully you won't be able to publish the package -- that would be a security issue, hehe :)

**Comment by BirdyF** [comment]
Ok. I will try next week as I am away from my keyboard.

**Comment by BirdyF** [comment]
@jonasfj  I tried convert-master. 
flutter packages pub publish --dry-run is working fine.
So the problem is coming from my package I suppose.

**Comment by jonasfj** [comment]
Hmm, that's interesting :)

**Comment by jonasfj** [comment]
Hmm, I have no problem doing a `pub publish --dry-run`

**Comment by BirdyF** [comment]
So the problem could come from my Flutter installation?

**Comment by jonasfj** [comment]
Maybe, it could also be we're running different versions of pub, and that we're on different systems.

Another way to debug this would be to clone this repository, and try to run tests locally.

**Comment by NamJangHyuk** [comment]
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_svg: 0.14.0
  webview_flutter: ^0.3.10+4

Try to input package code below cupertino...

**Comment by Asma-cloud** [comment]
[small_app] flutter packages get
Running "flutter pub get" in small_app...                       
Error on line 21, column 5 of pubspec.yaml: A dependency may only have one source.

   ╷

21 │ ┌     sdk: flutter

22 │ │     

23 │ │     cupertino_icons: ^0.1.2

24 │ │     http: any








25 │ │ 
26 │ │     
27 │ │ 
28 │ │   # The following adds the Cupertino Icons font to your application.
29 │ │   # Use with the CupertinoIcons class for iOS style icons.
30 │ │   cupertino_icons: ^0.1.2
   │ └──^
   ╵
pub get failed (65;    ╵)
exit code 65
 this problem came in my pubspec.yml .i did not get http package how i can solved guide me

**Comment by jonasfj** [comment]
@Asma-cloud, looks like you've listed `cupertino_icons` twice :)
(I'm just guessing)

Please file new issues instead of commenting on unrelated issues. For general support please consider stackoverflow, or one of the other community forums...

**Comment by sensibleBiz** [comment]
> I am trying to publish my first package (https://github.com/BirdyF/strava_flutter) and have the following error:
> pub finished with exit code 65
> 
> When running flutter packages pub publish --dry-run --verbose the detailed error is:
> | Nothing output on stderr.
> IO : Reading binary file ./README.md.
> IO : Read 1537 bytes from ./README.md.
> IO : Spawning "tar --format=ustar --create --gzip --directory /Users/user/Documents/Flutter/packages/strava_flutter/. @/dev/stdin" in /Users/user/Documents/Flutter/packages/strava_flutter/.
> WARN: Suggestions:
> WARN: * The name of "lib/API/Oauth.dart", "Oauth", should be lower-case. Maybe use "oauth"?
> WARN: * The name of "lib/Models/detailedActivity.dart", "detailedActivity", should be lower-case. Maybe use "detailed_activity"?
> WARN: * The name of "lib/Models/detailedAthlete.dart", "detailedAthlete", should be lower-case. Maybe use "detailed_athlete"?
> WARN: * The name of "lib/Models/runningRace.dart", "runningRace", should be lower-case. Maybe use "running_race"?
> WARN: * The name of "lib/Models/startSegment.dart", "startSegment", should be lower-case. Maybe use "start_segment"?
> WARN: * The name of "lib/Models/summaryActivity.dart", "summaryActivity", should be lower-case. Maybe use "summary_activity"?
> WARN: * The name of "lib/Models/summaryAthlete.dart", "summaryAthlete", should be lower-case. Maybe use "summary_athlete"?
> WARN: * The name of "lib/Models/uploadActivity.dart", "uploadActivity", should be lower-case. Maybe use "upload_activity"?
> WARN:
> | Package has 8 warnings.
> pub finished with exit code 65
> 
> ```
> #0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
> #1      pubInteractively (package:flutter_tools/src/dart/pub.dart:186:5)
> <asynchronous suspension>
> #2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:148:11)
> <asynchronous suspension>
> #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
> #4      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
> #5      _rootRunUnary (dart:async/zone.dart:1132:38)
> #6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
> #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
> #9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
> #10     Future._complete (dart:async/future_impl.dart:473:7)
> #11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
> #12     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
> #13     _rootRun (dart:async/zone.dart:1124:13)
> #14     _CustomZone.run (dart:async/zone.dart:1021:19)
> #15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
> #16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> #18     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
> #19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
> ```
> 
> Here is below flutter doctor
> 
> ```
> [✓] Flutter (Channel stable, v1.0.1-pre.2, on Mac OS X 10.13.6 17G3025, locale en-BE)
>     • Flutter version 1.0.1-pre.2 at /Users/user/Documents/Flutter/flutter
>     • Framework revision 27cb0aca17 (32 minutes ago), 2019-03-05 09:47:35 +0100
>     • Engine revision 3757390fa4
>     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/user/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.1, Build version 10B61
>     • ios-deploy 1.9.4
>     • CocoaPods version 1.5.3
> 
> [!] Android Studio (version 3.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [✓] VS Code (version 1.30.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 2.24.0
> 
> [✓] Connected device (1 available)
>     • ANE LX1 • 89UDU18531001686 • android-arm64 • Android 8.0.0 (API 26)
> ```
> 
> Not sure what I have done incorrectly

Make Sure (flutter/ intl/ google in same indentation) ✅

If it is in line with (sdk: flutter) ✖ pub finished with exit code 65

--
dependencies:
  flutter:
    sdk: flutter  
  intl: ^0.16.1
  google_fonts: ^0.4.0

**Comment by vyasswati** [comment]
Error on line 25, column 5 of pubspec.yaml: A dependency may only have one source
